### ISSUE TITLE
Checking value types

### ISSUE THREAD

**Issue by SultanOrazbayev** [kensho-technologies/qwikidata#16]
I sometimes come across the following error:
````
ValueError: required qualifier_dict keys are ['hash', 'snaktype', 'property', 'datavalue', 'datatype']. only found ['snaktype', 'property', 'hash', 'datatype']
````
This arises when running command `get_truthy_claim_group`, it seems that for some properties `datavalue` is not available as a dictionary key.

**Comment by galtay** [comment]
Thanks for the report!  This is failing for Qualifiers that have snaktype of `somevalue` or `novalue` (as opposed to `value`).  Will update today.

**Comment by SultanOrazbayev** [comment]
Thanks!

**Comment by galtay** [comment]
v0.1.5 which includes this fix is on PyPI now.
https://pypi.org/project/qwikidata/0.1.5/
