### ISSUE TITLE
dump_entities_to_json fails if entities has only one member

### ISSUE THREAD

**Issue by galtay** [kensho-technologies/qwikidata#29]
https://github.com/kensho-technologies/qwikidata/blob/develop/qwikidata/utils.py#L33

`ent_hi` will be undefined

**Comment by kunaltawatia** [comment]
Hey @galtay,
If this issue is still open, may I attempt to resolve this?

PS: This repository has helped ease up things in my project.

**Comment by galtay** [comment]
Yes, please do! Glad the package helped you in your work.
