### ISSUE TITLE
Exception from`return_sparql_query_results`

### ISSUE THREAD

**Issue by sefeoglu** [kensho-technologies/qwikidata#32]
Hello,

I am using your qwikidata for the last part of my thesis. The function `return_sparql_query_results` returns an exception for all queries since today afternoon. When I run the SPARQL from Wikidata Query service interface, it returns the results.
Could you check this function ?

Thank in advance. 
Best Regards.

**Comment by galtay** [comment]
Hello sefeoglu, 

Thanks for posting the issue. It may be that the service is banning your query. Can you try the following and show the results? 

```python
wikidata_sparql_url = "https://query.wikidata.org/sparql"
query_string = "... your query ..."
response = requests.get(wikidata_sparql_url, params={"query": query_string, "format": "json"})
print(response.text)
```

**Comment by sefeoglu** [comment]
Thank you for your help,

I have been banned until tomorrow, so I think there is no problem on your function. 

Thank you again.
